### PR TITLE
Added optional JsonSerializer

### PR DESCRIPTION
**Pull request by radiant-alex**

### CODE REVIEW

**Comment by radiant-alex** [comment]
The reason of this PR is this call 
`await client.ExchangesClient.GetTickerByExchangeId("uniswap_arbitrum");`

It will fail with an error that one of its floating point values is out of decimal range. That is why handling that in custom decimals' Json serialiser

**Comment by tosunthex** [comment]
@radiant-alex thank you for your help and fixed the codacy problems 👍

**Comment by radiant-alex** [comment]
Thanks a lot! 
When NuGet package will be released?

**Comment by tosunthex** [comment]
I already made it. But you must little bit wait for indexing the package by Nuget ;)

**Pull request merged**
